owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/misc"
homepage_url: "TODO"
categories:
  - Metabolomics
repositories:
  riassigner:
    description: "TODO"
    long_description: |
      "TODO"
    include:
      - use_theoretical_mz_annotations.xml
      - macros.xml
      - test-data
