owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/msp_merge"
homepage_url: "https://github.com/RECETOX/galaxytools"
categories:
  - Metabolomics
repositories:
  msp_merge:
    description: "Utility tool to merge  individual `msp` spectra files in a collection into a single file."
    long_description: "MSPmerge handles input/output files in MSP format using the matchms.importing and matchms.exporting modules"
    include:
      - msp_merge.xml
      - msp_merge.py
      - test-data
